name: CD - Déploiement GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      # Publie TOUT le repo (la racine) vers Pages
      - name: Préparer l’artefact Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
